### ISSUE TITLE
🚨 [Bug] 다중 게임 실시간 렌더링 안됨 버그

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#102]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

다중 게임 실시간 렌더링 안됨 버그

## 🐞 버그 상세 내용

다중 게임 실시간 렌더링 안됨 버그
-> 게임 방 이름을 map으로 관리
-> ready emit 이벤트 중복 수정

## ✅ TODO

- [x] 다중 게임 실시간 렌더링 안됨 버그 수정
