### ISSUE TITLE
♻️ [Refactor] 코드 인증 유저 정보 쿠키 대신 state로 관리

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#104]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 코드 인증 유저 정보 쿠키 대신 state로 관리

## 📝 리팩토링 상세 내용

- 코드 인증 유저 정보 쿠키 대신 state로 관리

## ✅ TODO

- [x] 코드 인증 유저 정보 쿠키 대신 state로 관리
