### ISSUE TITLE
✨[Feature] 게임 관전 프론트

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#105]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 프론트에서 게임 관전 기능 추가
- 
## 📝 기능 상세 내용

- 관전 원하는 gameWatchId를 백엔드로 보내고 그 결과에 따라 관전

## ✅ TODO

- [x] gameWatchId와 client 정보 백으로 보내기
- [x] 소켓 on으로 결과 받기
