### ISSUE TITLE
♻️ [Refactor] 채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#109]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력

## 📝 리팩토링 상세 내용

- 채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력

## ✅ TODO

- [x] 채팅방 비번 수정 시 오너가 아닌 사람이 수정할 때 에러 화면 출력
