### ISSUE TITLE
✨[Feature] Global Style 작성, Theme 작성, 초기 CSS 설정 블록

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/FrontEnd#11]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- Global Style 작성
- Theme 작성
- 초기 CSS 설정 블록

## 📝 기능 상세 내용

프론트 개발을 위한 Global Style 등 스타일을 미리 정해두고 효율성을 올리기 위함

## ✅ TODO

- [x] Global Style 작성
- [x] Theme 작성
- [x] 초기 CSS 설정 블록
