### ISSUE TITLE
♻️ [Refactor] friends 기능 에러 모달 사용

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#115]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- friends 기능 에러 모달 사용

## 📝 리팩토링 상세 내용

- friends 기능 에러 모달 사용

## ✅ TODO

- [x] friends 기능 에러 모달 사용
