### ISSUE TITLE
🚨 [Bug] 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 해결

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#119]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제

## 🐞 버그 상세 내용

- 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 

## ✅ TODO

- [x] 내가 속한 채널이 없을 경우 에러 모달 출력되는 문제 해결
