### ISSUE TITLE
🚨 [Bug] 게임 샵 에러 해결

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#121]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 게임 샵 에러 해결

## 🐞 버그 상세 내용

- 구매한 게임의 buy 버튼을 누를 수 없게 해야 함.
- 게임을 선택 안하고 관전하기 누르는 거 막아야 함.

## ✅ TODO

- [x] 구매한 게임의 buy 버튼을 누를 수 없게 해야 함.
- [x] 게임을 선택 안하고 관전하기 누르는 거 막아야 함.
