### ISSUE TITLE
♻️ [Refactor] 백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#128]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정

## 📝 리팩토링 상세 내용

백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정
## ✅ TODO

- [x] 백엔드 url(localhost, 127.0.0.1) env 변수 사용하도록 수정
