### ISSUE TITLE
♻️ [Refactor] 404 에러 처리

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#130]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 404 에러 처리

## 📝 리팩토링 상세 내용

- 404 에러 처리

## ✅ TODO

- [x] 404 에러 페이지 생성
- [x] url의 uuid 형식 확인
