### ISSUE TITLE
🚨 [Bug] 관리자가 아닌 유저가 관리자 설정했을 경우 처리

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#132]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

관리자가 아닌 유저가 관리자 설정했을 경우 처리

## 🐞 버그 상세 내용

관리자가 아닌 유저가 관리자 설정했을 경우 처리

## ✅ TODO

- [x] 관리자가 아닌 유저가 관리자 설정했을 경우 처리
