### ISSUE TITLE
🚨 [Bug] 게임 준비 취소

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#140]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

상대방이 게임 준비 중 나갔을 때의 처리

## ✅ TODO

- [x] 게임 준비 중 상대방의 취소 처리
