### ISSUE TITLE
♻️ [Refactor] 게임 페이지 console.error -> error 모달 수정

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#145]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 게임 페이지 console.error -> error 모달 수정

## 📝 리팩토링 상세 내용

- 게임 페이지 console.error -> error 모달 수정

## ✅ TODO

- [x] 게임 페이지 console.error -> error 모달 수정
