### ISSUE TITLE
✨[Feature] 이슈 템플릿 재 업로드

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/FrontEnd#153]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 브런치 병합 하면서 템플릿 사라진 것 재 업로드

## ✅ TODO

- [x] 템플릿 사라진 것 재 업로드
