### ISSUE TITLE
♻️ [Refactor]게임 로직 any 타입 제거

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#156]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 프론트 코드 상 any 타입 제거

## 📝 리팩토링 상세 내용

- any 타입 제거

## ✅ TODO

- [x] any 타입 본 타입으로 변경
