### ISSUE TITLE
✨[Feature] 공개채널 페이지

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#17]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 추가할 기능 요약 설명

## 📝 기능 상세 내용

- 공개된 채널(채팅방)의 목록을 보여주는 페이지 + 토글버튼 + 방 생성 세팅 모달

## ✅ TODO

- [x] 공개 채널 목록
- [x] 토글버튼
- [x] 채널 생성 모달
