### ISSUE TITLE
✨[Feature] 소켓 게임플레이

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#22]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 소켓 연결된 게임플레이 화면을 구현

## 📝 기능 상세 내용

- 핌퐁게임을 구현하고, 점수와 플레이어를 상단에 표기.

## ✅ TODO

- [x] 게임 소켓 연결
- [x] 게임 플레이 화면
