### ISSUE TITLE
♻️ [Refactor] 헤더/푸터 이전 페이지 기억

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#24]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 헤더/푸터 이전 페이지 기억

## 📝 리팩토링 상세 내용

- 헤더/푸터 이전 페이지 기억

## ✅ TODO

- [ ] 헤더/푸터 이전 페이지 기억

**Comment by cofls980** [comment]
페이지들이 다 만들어지면 추가
