### ISSUE TITLE
✨[Feature] 내가 속한 채널 페이지

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#25]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 내가 속한 채널 페이지 목록

## 📝 기능 상세 내용

- 내가 속한 채널 페이지 목록 나열
- 목록에 프로필 사진도 함께 구현

## ✅ TODO

- [x] 내가 속한 채널 페이지 목록
- [x] 채널 별 대표 프로필 사진 추가
- [x] 마지막 메시지 시간 표시
- [x] 채널 별 참여자 리스트 표시
