### ISSUE TITLE
✨[Feature] 친구 상세 프로필 & 게임 플레이 모달 틀

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#29]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임 플레이 모달 작업용 친구 상세 프로필 페이지 틀

## 📝 기능 상세 내용

- 틀을 잡기 위해 간단히 플레이 버튼만 구현하여 모달을 구현

## ✅ TODO

- [x] 틀 잡아놓기
- [x] 플레이 버튼 -> 모달 구현
