### ISSUE TITLE
🚨 [Bug] 공개채널 페이지

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#30]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 비밀번호 공개방 입장시 비밀번호 없음
- 입장시 내가 속한 채널 페이지 목록 추가 안 됨

## 🐞 버그 상세 내용

- 비밀번호를 쳐야 들어갈 수 있도록 해야 함.
- 입장 시 내가 속한 채널로 만들어주지 않아, 입장 후에도 내가 속한 체널 페이지 목록에 없음

## ✅ TODO

- [ ] 비밀번호 방 비밀번호 입력 모달 추가
- [ ] 방 입장시 내가 속한 채널 페이지 목록에 추가
