### ISSUE TITLE
✨[Feature] 게임레디 모달

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#33]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임레디 모달

## 📝 기능 상세 내용

- 선택된 게임을 바탕으로 게임 레디 모달을 만듦

## ✅ TODO

- [x] 게임 모달 디브 만들기 
- [x] 게임 관련 state 관리
- [x] 게임 플레이 클릭 시 게임 화면 전환
