### ISSUE TITLE
♻️ [Refactor] 프로필 수정 파일 선택과 이미지 프리뷰 css 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#35]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

-  프로필 수정 파일 선택과 이미지 프리뷰 부분 css 수정

## 📝 리팩토링 상세 내용

- 프로필 수정 부분의 이미지 업로드 관련 부분의 css가 아직 구현을 못함. 추후에 수정하려고 함

## ✅ TODO

- [x] 파일 선택 input을 꾸미기
- [x] 이미지 프리뷰에 기존 유저 이미지 or 업로드한 이미지가 뜨도록 해야함
- [x] recoil로 저장한 userInfo를 사용하도록 수정
