### ISSUE TITLE
✨[Feature] 게임 구매 페이지, 게임 구매 모달 구현

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#36]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임 구매 페이지 구현
- 게임 구매 모달 구현

## 📝 기능 상세 내용

- 게임 구매 페이지 구현
- 게임 구매 모달 구현

## ✅ TODO

- [x] 게임 구매 페이지 구현
- [x] 게임 구매 모달 구현
