### ISSUE TITLE
✨[Feature] 채팅방 사이드 모달 구현

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#46]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 채팅방 사이드 모달 구현
- 채팅방의 다른 모달들과 연결
- axios에서 react-query로 수정 -> 채팅방 멤버 정보 실시간으로 업데이트

## ✅ TODO

- [x] 채팅방 사이드 모달 구현
- [x] 채팅방의 다른 모달들과 연결
- [x] axios에서 react-query로 수정 -> 채팅방 멤버 정보 실시간으로 업데이트
