### ISSUE TITLE
♻️ [Refactor] css 리팩토링

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#49]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 높이를 고려하지 않고 짠 부분이 많기에 수정해야 함 -> 일단 스크롤이 되긴 하니 시간 날 때!!

## 📝 리팩토링 상세 내용

- 게임 구매, 마이 페이지 높이 신경 써서 css 리팩토링

## ✅ TODO

- [x] 게임 구매 페이지
- [x] 마이 페이지
