### ISSUE TITLE
✨[Feature] 친구목록 페이지 만들기

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/FrontEnd#54]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

친구목록 페이지
- 본인 프로필 클릭시 마이페이지로 이동
- 친구 프로필 클릭시 친구 프로필 보여주기
- 친구추가 시 친구추가 페이지로 이동시켜주기

## ✅ TODO

- [x] 본인 프로필 클릭시 마이페이지로 이동
- [ ] 친구 프로필 클릭시 친구 프로필 보여주기
- [ ] 친구추가 시 친구추가 페이지로 이동시켜주기
