### ISSUE TITLE
✨[Feature] 친구 페이지 - 친구 추가

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#59]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 친구 페이지 - 친구 추가

## 📝 기능 상세 내용

- 친구 페이지 - 친구 추가

## ✅ TODO

- [x] 친구 페이지 - 친구 추가

**Comment by cofls980** [comment]
모달로 변경
