### ISSUE TITLE
✨[Feature] 채팅방페이지

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/FrontEnd#6]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

채팅방 페이지 구현

## ✅ TODO

- [ ] 리액트를 이용한 채팅방 페이지 구현
