### ISSUE TITLE
♻️ [Refactor] 기존 axios 코드를 react-query로 변경

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#60]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 기존 axios 코드를 react-query로 변경

## 📝 리팩토링 상세 내용

- 기존 axios 코드를 react-query로 변경

## ✅ TODO

- [x] 게임 정보 Get
- [x] 게임 구매 Post
