### ISSUE TITLE
🚨 [Bug] 핑퐁게임 프론트엔드 렌더링

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#63]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 게임 렌더링이 이상하게 나오는 이슈

## 🐞 버그 상세 내용

- 아래 패들이 이상하게 나옴

## ✅ TODO

- [x] 패들 렌더링 위치 수정함
