### ISSUE TITLE
✨[Feature] 게임 초대 수락 모달과 게임 초대 기능 구현

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#65]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

게임 초대 수락 모달, 게임 초대 기능 구현 

## 📝 기능 상세 내용

- 특정 유저에게 게임 초대를 했을 시 초대 받은 유저의 화면에 게임 수락 모달이 뜨도록 함
- 초대 수락했을 시 게임 준비 모달이 뜨게함
- 여러 경우의 에러 처리
  자기 자신
  로그인 안된 유저
  여러 명이 한 명에게 요청 보내면 문제가 생길 것 같음 -> 모달이 덮어씌어짐. 괜찮을 듯
  게임을 구매하지 않은 유저
  이미 게임 중
  게임 준비 중...인 유저는 그냥 status를 game으로 바꾸는 것도 좋아 보임...

## ✅ TODO

- [x] 게임 초대 수락 모달
- [x] 초대 받은 유저의 화면에 게임 초대 수락 모달이 뜸
- [x] 자기 자신, 로그인 안된 유저, 게임을 구매하지 않은 유저인 경우의 에러 처리
- [x] 게임 중, 게임 준비 중인 유저인 경우 에러 처리
