### ISSUE TITLE
✨[Feature] 친구 프로필 - dm 채팅

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#70]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 친구 프로필 - dm 채팅

## 📝 기능 상세 내용

- 친구 프로필 - dm 채팅

## ✅ TODO

- [ ] 친구 프로필 - dm 채팅
