### ISSUE TITLE
♻️ [Refactor] 마이 페이지 게임 선택 상태 관리 코드 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/FrontEnd#84]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 마이 페이지 게임 선택 상태 관리 코드 수정

## 📝 리팩토링 상세 내용

상태 관리를 게임 이름 -> 게임 id로 수정

## ✅ TODO

- [x] 마이 페이지 게임 선택 상태 관리 코드 수정
