### ISSUE TITLE
✨[Feature] 게임 관전 페이지와 게임 전적 페이지 구현

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/FrontEnd#86]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 추가할 기능 요약 설명

## 📝 기능 상세 내용

게임 관전 페이지와 게임 전적 페이지 구현
게임 관전 페이지는 게임으로 이동시켜주어야 함

## ✅ TODO

- [ ] 게임 관전 페이지 구현
- [ ] 게임 전적 페이지 구현
