### ISSUE TITLE
🚨 [Bug] 채팅방 내에서 프로필 눌렀을 때만 isAdmin api 요청 사용

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#91]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 친구 목록에서 프로필 눌렀을 때 필요없는 isAdmin api 요청 발생

## 🐞 버그 상세 내용

- 친구 목록에서 프로필 눌렀을 때 필요없는 isAdmin api 요청 발생
## ✅ TODO

- [x]  isAdmin api 요청을 채팅방 내에서 프로필 눌렀을 때만 적용하게 하기.
