### ISSUE TITLE
✨[Feature] 게임 socket room 구분

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/FrontEnd#93]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임이 여러개 플레이될 때 구분

## 📝 기능 상세 내용

- socket.io의 room기능을 이용해 게임들을 구분

## ✅ TODO

- [x] room기능 추가
- [x] 게임 2개 이상 테스트
