### ISSUE TITLE
♻️ [Refactor] 채팅방에서 url 경로의 채널 아이디 사용

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#94]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 채팅방에서 url 경로의 채널 아이디 사용

## 📝 리팩토링 상세 내용

- 새로고침할 때 리코일에 있는 채널 아이디가 초기화 되는 문제 때문에 채팅방에서 url 경로의 채널 아이디 사용

## ✅ TODO

- [x] 채팅방에서 url 경로의 채널 아이디 사용
