### ISSUE TITLE
🚨 [Bug] ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는 문제

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/FrontEnd#98]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는다.

## 🐞 버그 상세 내용

- ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는다.

## ✅ TODO

- [ ] ProfileFooter의 mute 아이콘이 바로바로 적용되지 않는다.
